# Generated by Django 5.0.4 on 2024-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedata',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
