# Generated by Django 5.0.4 on 2024-04-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startYear', models.IntegerField()),
                ('endYear', models.IntegerField()),
                ('instituteName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
            ],
        ),
    ]
